AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.moia.drivers.shift.demo.Main
      CodeUri: ./build/libs/kotlin-sample-all.jar
      Runtime: java8
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get